interface Props {
  /** art is the picture, generated by tools/genicons.py from its master in assets. */
  art: string
  /** label names what pressing it does: the tooltip and the accessible name. */
  label: string
  /** large draws the artwork at the large height genicons renders it for. */
  large?: boolean
  onClick: () => void
}

/** The Add city button's tooltip and accessible name, shared by the ribbon and Settings. */
export const addCityTip = 'Add a city: search by its name, region or country'

/** ArtButton is a button whose face is artwork, drawn at the height genicons renders it for. */
export function ArtButton({ art, label, large = false, onClick }: Props) {
  return (
    <button type="button" className={large ? 'art large' : 'art'} title={label} aria-label={label} onClick={onClick}>
      <img src={art} alt="" draggable={false} />
    </button>
  )
}
