package application

// symbolWords names each of the 41 symbols in MET Norway's legend.csv as an everyday forecast says
// it, as a sentence begins (FR-412, NFR-U-2), keyed by the symbol's correct spelling without its
// variant: showers alone are of rain, showers with thunder are thundery. The variant is not said:
// the icon itself draws the sun or the moon.
var symbolWords = map[string]string{
	"clearsky":                    "Clear skies",
	"fair":                        "Mostly clear",
	"partlycloudy":                "Partly cloudy",
	"cloudy":                      "Cloudy",
	"fog":                         "Fog",
	"lightrain":                   "Light rain",
	"rain":                        "Rain",
	"heavyrain":                   "Heavy rain",
	"lightrainandthunder":         "Light rain and thunder",
	"rainandthunder":              "Rain and thunder",
	"heavyrainandthunder":         "Heavy rain and thunder",
	"lightrainshowers":            "Light showers",
	"rainshowers":                 "Showers",
	"heavyrainshowers":            "Heavy showers",
	"lightrainshowersandthunder":  "Light thundery showers",
	"rainshowersandthunder":       "Thundery showers",
	"heavyrainshowersandthunder":  "Heavy thundery showers",
	"lightsleet":                  "Light sleet",
	"sleet":                       "Sleet",
	"heavysleet":                  "Heavy sleet",
	"lightsleetandthunder":        "Light sleet and thunder",
	"sleetandthunder":             "Sleet and thunder",
	"heavysleetandthunder":        "Heavy sleet and thunder",
	"lightsleetshowers":           "Light sleet showers",
	"sleetshowers":                "Sleet showers",
	"heavysleetshowers":           "Heavy sleet showers",
	"lightsleetshowersandthunder": "Light thundery sleet showers",
	"sleetshowersandthunder":      "Thundery sleet showers",
	"heavysleetshowersandthunder": "Heavy thundery sleet showers",
	"lightsnow":                   "Light snow",
	"snow":                        "Snow",
	"heavysnow":                   "Heavy snow",
	"lightsnowandthunder":         "Light snow and thunder",
	"snowandthunder":              "Snow and thunder",
	"heavysnowandthunder":         "Heavy snow and thunder",
	"lightsnowshowers":            "Light snow showers",
	"snowshowers":                 "Snow showers",
	"heavysnowshowers":            "Heavy snow showers",
	"lightsnowshowersandthunder":  "Light thundery snow showers",
	"snowshowersandthunder":       "Thundery snow showers",
	"heavysnowshowersandthunder":  "Heavy thundery snow showers",
}
