package application

// symbolWords names each of the 41 symbols in MET Norway's legend.csv in English as a sentence
// begins (FR-412, NFR-U-2), keyed by the symbol's correct spelling without its variant. The variant
// is not said: the icon itself draws the sun or the moon.
var symbolWords = map[string]string{
	"clearsky":                    "Clear sky",
	"fair":                        "Fair",
	"partlycloudy":                "Partly cloudy",
	"cloudy":                      "Cloudy",
	"fog":                         "Fog",
	"lightrain":                   "Light rain",
	"rain":                        "Rain",
	"heavyrain":                   "Heavy rain",
	"lightrainandthunder":         "Light rain and thunder",
	"rainandthunder":              "Rain and thunder",
	"heavyrainandthunder":         "Heavy rain and thunder",
	"lightrainshowers":            "Light rain showers",
	"rainshowers":                 "Rain showers",
	"heavyrainshowers":            "Heavy rain showers",
	"lightrainshowersandthunder":  "Light rain showers and thunder",
	"rainshowersandthunder":       "Rain showers and thunder",
	"heavyrainshowersandthunder":  "Heavy rain showers and thunder",
	"lightsleet":                  "Light sleet",
	"sleet":                       "Sleet",
	"heavysleet":                  "Heavy sleet",
	"lightsleetandthunder":        "Light sleet and thunder",
	"sleetandthunder":             "Sleet and thunder",
	"heavysleetandthunder":        "Heavy sleet and thunder",
	"lightsleetshowers":           "Light sleet showers",
	"sleetshowers":                "Sleet showers",
	"heavysleetshowers":           "Heavy sleet showers",
	"lightsleetshowersandthunder": "Light sleet showers and thunder",
	"sleetshowersandthunder":      "Sleet showers and thunder",
	"heavysleetshowersandthunder": "Heavy sleet showers and thunder",
	"lightsnow":                   "Light snow",
	"snow":                        "Snow",
	"heavysnow":                   "Heavy snow",
	"lightsnowandthunder":         "Light snow and thunder",
	"snowandthunder":              "Snow and thunder",
	"heavysnowandthunder":         "Heavy snow and thunder",
	"lightsnowshowers":            "Light snow showers",
	"snowshowers":                 "Snow showers",
	"heavysnowshowers":            "Heavy snow showers",
	"lightsnowshowersandthunder":  "Light snow showers and thunder",
	"snowshowersandthunder":       "Snow showers and thunder",
	"heavysnowshowersandthunder":  "Heavy snow showers and thunder",
}
